[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
ar = "arm-linux-gnueabihf-ar"     # optional

# https://betterprogramming.pub/cross-compiling-rust-from-mac-to-linux-7fad5a454ab1
[target.random-linux-libc]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[profile.profiling]
inherits = "release"
debug = true
